document.querySelector(".soaring").addEventListener("click",()=>{window.open("https://www.youtube.com/@soarinngchu")})
document.querySelector(".duxo").addEventListener("click",()=>{window.open("https://www.youtube.com/@DUXO")})
document.querySelector(".mictia").addEventListener("click",()=>{window.open("https://www.youtube.com/@Mictia00")})
document.querySelector(".loco").addEventListener("click",()=>{window.open("https://www.youtube.com/@lLocochon")})
document.querySelector(".andreh").addEventListener("click",()=>{window.open("https://www.youtube.com/@andrehplus")})
document.querySelector(".michu").addEventListener("click",()=>{window.open("https://www.youtube.com/@EsMichu")})
document.querySelector(".lucasta").addEventListener("click",()=>{window.open("https://www.youtube.com/@LucastaYT")})
document.querySelector(".nat").addEventListener("click",()=>{window.open("https://www.youtube.com/@Natalan")})
document.querySelector(".estailus").addEventListener("click",()=>{window.open("https://www.youtube.com/@EstailusVR")})
document.querySelector(".cejo").addEventListener("click",()=>{window.open("https://www.youtube.com/@c3jotct")})
document.querySelector(".emi").addEventListener("click",()=>{window.open("https://www.youtube.com/@EmikukisCH")})
document.querySelector(".kendo").addEventListener("click",()=>{window.open("https://www.youtube.com/@KendoMurft")})
document.querySelector(".fery").addEventListener("click",()=>{window.open("https://www.youtube.com/@feryfer")})
document.querySelector(".meica").addEventListener("click",()=>{window.open("https://www.youtube.com/@Meiiica")})
document.querySelector(".tomy").addEventListener("click",()=>{window.open("https://www.youtube.com/@TomyCatts")})
document.querySelector(".sylvi").addEventListener("click",()=>{window.open("https://www.youtube.com/@Sylveey")})
document.querySelector(".pelee").addEventListener("click",()=>{window.open("https://www.youtube.com/@Dtowncat")})


